name: Auto Build Android APK

on:
  push:
    branches: ['main']

jobs:
  update:
    type: update
    params:
      branch: preview
      message: "Auto update from commit"
  deploy:
    type: deploy
    params:
      profile: preview
  # build_android:
  #   type: build
  #   params:
  #     platform: android
  #     profile: preview