name: Auto Build Android APK

on:
  push:
    branches: ['main']

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: preview
  # update:
  #   type: update
  #   params:
  #     branch: preview
  #     message: "Auto update from commit"